// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twkqxsbrrwodkgqqfhno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3a3F4c2JycndvZGtncXFmaG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzg1NjgsImV4cCI6MjA2MjcxNDU2OH0.Dtmt4ApmiXDWotjh0VyXn2_2NoRq8-TcWTEqgUJ72Pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);